# Generated by Django 4.1.2 on 2022-10-20 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='media/image/')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('brand', models.ManyToManyField(to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('cover', models.ImageField(upload_to='media/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (1, 'XL')])),
                ('color', models.CharField(max_length=123)),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField()),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cap')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(default='2999-12-31')),
                ('is_active', models.BooleanField(default=True)),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cap')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/image/')),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cap')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField()),
                ('total', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=123)),
                ('status', models.BooleanField(default=True)),
                ('stock', models.ManyToManyField(to='app.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
