# Generated by Django 4.1.2 on 2022-10-21 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='brand',
            field=models.ManyToManyField(related_name='caps', to='app.brand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock',
            field=models.ManyToManyField(related_name='orders', to='app.stock'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.cap'),
        ),
        migrations.AlterField(
            model_name='price',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.cap'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.cap'),
        ),
    ]
