# Generated by Django 4.1.2 on 2022-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cap_brand_alter_order_stock_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
