# Generated by Django 4.1.2 on 2022-10-21 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_price_end_date_alter_price_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 31, 12, 0, 59)),
        ),
    ]
