# Generated by Django 4.1.2 on 2022-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_detailphoto_orderdetail_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Данный товар активен'),
        ),
    ]
