# Generated by Django 4.1.2 on 2022-10-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cap_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
        migrations.AlterModelOptions(
            name='cap',
            options={'verbose_name': 'Кепка', 'verbose_name_plural': 'Кепки'},
        ),
        migrations.AlterModelOptions(
            name='detailphoto',
            options={'verbose_name': 'Детальное фото', 'verbose_name_plural': 'Детальные фотки'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Детальный заказ', 'verbose_name_plural': 'Детальный заказ'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
    ]
