# Generated by Django 4.1.2 on 2022-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_brand_options_alter_cap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата старта цены'),
        ),
    ]
