# Generated by Django 4.1.2 on 2022-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_price_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В обработке'), (2, 'Заказ не принят'), (3, 'Заказ принят')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.PositiveIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], verbose_name='Размер'),
        ),
    ]
